/mujoco_ros_sim_node:
  ros__parameters:
    task_gains:
      kp:
        - 100.0 # x
        - 100.0 # y
        - 100.0 # z
        - 100.0 # r
        - 100.0 # p
        - 100.0 # y
      kv:
        - 20.0 # x
        - 20.0 # y
        - 20.0 # z
        - 20.0 # r
        - 20.0 # p
        - 20.0 # y

    QPIK_gains:
      tracking:
        - 1.0 # x
        - 1.0 # y
        - 1.0 # z
        - 1.0 # r
        - 1.0 # p
        - 1.0 # y
      damping:
        - 1.0 # joint 1
        - 1.0 # joint 2
        - 1.0 # joint 3
        - 1.0 # joint 4
        - 1.0 # joint 5
        - 1.0 # joint 6
      # TODO: set QPIK joint acceleration damping weights (added in dyros_robot_controller)
      acc_damping:
        - 0.0 # joint 1
        - 0.0 # joint 2
        - 0.0 # joint 3
        - 0.0 # joint 4
        - 0.0 # joint 5
        - 0.0 # joint 6
